# Generated by Django 5.2.3 on 2025-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
